import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from "next/font/google";
import ThemeRegistry from "./ThemeRegistry";

const roboto = Roboto({
  weight: ['300', '400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
        <div className="bg-gray-100 h-screen p-1">
          <ThemeRegistry>
            {children}
          </ThemeRegistry>
        </div>
      </body>
    </html>
  );
}